# Site settings
author: Andrew Ribas
title: 
header-img: img/home-bg.png
email: andrew.j.ribas@gmail.com
copyright_name: Andrew Ribas
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Directrix777

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
